import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyState, transition, digest, actions } from '../skills/woia-re-listing-distribution/scripts/publication.mjs';

function fixture() {
 const state = emptyState('org');
 const command = {org:'org', action:actions[0], publicationId:'pub', operationId:'op', expectedRevision:0, payload:{channelAccountRef:'portal',listingVersionRef:'lv1',listingDigest:'content',mediaDigest:'media'}};
 const context = {org:'org',principal:'actor',department:'marketing',hold:false,emergencyStop:false,authorizedActions:actions,sourceMapRevision:'map1',policyRevision:'policy1',now:'2026-10-07T12:00:00Z',authoritativeChannelAccountRef:'portal',listingVersion:{org:'org',source:'woia-re-property-data',id:'lv1',digest:'content',mediaDigest:'media',accepted:true,current:true,mandateActive:true,rightsAccepted:true,mediaRightsAccepted:true}};
 context.grant={org:'org',principal:'actor',publicationId:'pub',purpose:'public-listing-distribution',actions,active:true,revoked:false,validFrom:'2026-10-07T00:00:00Z',validUntil:'2026-10-08T00:00:00Z'};
 context.sourceBinding={org:'org',publicationId:'pub',channelAccountRef:'portal',mapRevision:'map1',active:true,revoked:false,conflict:false,hold:false,validFrom:'2026-10-07T00:00:00Z',validUntil:'2026-10-08T00:00:00Z'};
 context.approval={id:'approval',revoked:false,competent:true,authorityEvidenceRef:'accepted-delegation',principal:'competent-owner',org:'org',action:command.action,publicationId:'pub',payloadDigest:digest({org:'org',action:command.action,publicationId:'pub',payload:command.payload}),policyRevision:'policy1',sourceMapRevision:'map1',validFrom:'2026-10-07T00:00:00Z',validUntil:'2026-10-08T00:00:00Z'};
 return {state,command,context};
}
test('intent is immutable, remote unknown and canonical Listing untouched',()=>{const f=fixture();const r=transition(f.state,f.command,f.context);assert.equal(f.state.revision,0);assert.equal(r.state.publications.pub.observed,'UNKNOWN');assert.equal(r.result.dispatchPerformed,false);assert.equal(r.state.effects.op.status,'UNKNOWN');});
for (const [label,change] of [
 ['cross org',f=>f.context.org='other'], ['scope',f=>f.context.authorizedActions=[]], ['Marketing executor',f=>f.context.department='sales'], ['revoked',f=>f.context.approval.revoked=true], ['self grant',f=>f.context.approval.principal='actor'], ['expiry',f=>f.context.approval.validUntil='2026-01-01'], ['policy changed',f=>f.context.policyRevision='new'], ['payload changed',f=>f.command.payload.mediaDigest='new'], ['revoked Mandate',f=>f.context.listingVersion.mandateActive=false], ['unaccepted rights',f=>f.context.listingVersion.rightsAccepted=false], ['media rights',f=>f.context.listingVersion.mediaRightsAccepted=false], ['source',f=>f.context.listingVersion.source='portal'], ['stale listing',f=>f.context.listingVersion.current=false], ['revision conflict',f=>f.command.expectedRevision=9], ['emergency stop',f=>f.context.emergencyStop=true], ['unsupported send',f=>f.command.action='person.send']
]) test(`reject ${label}`,()=>{const f=fixture();change(f);assert.throws(()=>transition(f.state,f.command,f.context));});
function observe(action='channel-publication.status.observe') { const f=fixture(); f.state=transition(f.state,f.command,f.context).state; f.command={...f.command,action,operationId:'observe1',expectedRevision:1,payload:{evidenceRef:'evidence1',sourceRevision:'remote1',remoteState:'PUBLISHED',observedAt:'2026-10-07T11:00:00Z',freshUntil:'2026-10-07T13:00:00Z'}}; return f; }
test('fresh observed publication remains separate from desired intent',()=>{const f=observe();const r=transition(f.state,f.command,f.context);assert.equal(r.result.status,'PUBLISHED');assert.equal(r.result.canonicalListingChanged,false);assert.equal(r.state.effects.op.status,'UNKNOWN');});
for(const field of ['freshUntil','observedAt']) test(`stale/future ${field} is UNKNOWN`,()=>{const f=observe();f.command.payload[field]=field==='freshUntil'?'2026-01-01':'2027-01-01';assert.equal(transition(f.state,f.command,f.context).result.status,'UNKNOWN');});
test('unknown outcome forbids replay and competing mutation',()=>{const f=fixture();f.state=transition(f.state,f.command,f.context).state;f.command.expectedRevision=1;assert.throws(()=>transition(f.state,f.command,f.context),/reconcile before retry/);f.command.operationId='another';assert.throws(()=>transition(f.state,f.command,f.context),/pending unknown/);});
test('reconcile exact operation permits deduplication',()=>{const f=observe('channel-publication.effect.reconcile');Object.assign(f.command.payload,{effectOperationId:'op',requestDigest:f.state.effects.op.requestDigest,outcome:'CONFIRMED'});const r=transition(f.state,f.command,f.context);const orig=fixture();orig.command.expectedRevision=r.state.revision;assert.equal(transition(r.state,orig.command,orig.context).result.status,'DEDUPLICATED');});
test('reconciliation cannot accept wrong operation payload',()=>{const f=observe('channel-publication.effect.reconcile');Object.assign(f.command.payload,{effectOperationId:'op',requestDigest:'wrong',outcome:'CONFIRMED'});assert.throws(()=>transition(f.state,f.command,f.context),/identity mismatch/);});
test('remote source mismatch denied',()=>{const f=observe();f.context.authoritativeChannelAccountRef='other';assert.throws(()=>transition(f.state,f.command,f.context));});
test('inbound normalized only to Communications/Customer Service',()=>{const f=observe('channel-publication.interaction.observe');Object.assign(f.command.payload,{interactionId:'i1',senderRef:'person1',contentRef:'immutable-content'});const r=transition(f.state,f.command,f.context);assert.deepEqual(r.result.interaction.route,{provider:'woia-communications',department:'customer-service',action:'communication.external.receive'});assert.equal(r.result.interaction.dispatchPerformed,false);f.command.expectedRevision=r.state.revision;assert.equal(transition(r.state,f.command,f.context).result.status,'DEDUPLICATED');});
for(const action of ['channel-publication.sync','channel-publication.withdraw']) test(`${action} prepares bound intent without rewriting observed state`,()=>{const f=fixture();f.state=transition(f.state,f.command,f.context).state;f.state.effects.op.status='CONFIRMED';f.command.action=action;f.command.operationId='op2';f.command.expectedRevision=1;f.context.approval.action=action;f.context.approval.payloadDigest=digest({org:'org',action,publicationId:'pub',payload:f.command.payload});const r=transition(f.state,f.command,f.context);assert.equal(r.result.status,'EFFECT_INTENT_PREPARED');assert.equal(r.state.publications.pub.observed,'UNKNOWN');assert.equal(r.state.publications.pub.desired,action.endsWith('withdraw')?'WITHDRAWN':'PUBLISHED');});
test('observation replay preserves immutable evidence',()=>{const f=observe();const r=transition(f.state,f.command,f.context);f.command.expectedRevision=r.state.revision;assert.equal(transition(r.state,f.command,f.context).result.status,'DEDUPLICATED');f.command.payload.evidenceRef='replacement';assert.throws(()=>transition(r.state,f.command,f.context),/identity conflict/);});
test('unaccepted authority fails',()=>{const f=fixture();f.context.approval.competent=false;assert.throws(()=>transition(f.state,f.command,f.context));});
test('reconciliation cannot claim completion with contradictory observation',()=>{const f=observe('channel-publication.effect.reconcile');Object.assign(f.command.payload,{effectOperationId:'op',requestDigest:f.state.effects.op.requestDigest,outcome:'CONFIRMED',remoteState:'WITHDRAWN'});assert.throws(()=>transition(f.state,f.command,f.context),/contradicts/);});
test('verified organization and publication keys cannot be overridden by observation payload',()=>{const f=observe();Object.assign(f.command.payload,{org:'other',publicationId:'other'});const r=transition(f.state,f.command,f.context);assert.equal(r.state.observations[0].org,'org');assert.equal(r.state.observations[0].publicationId,'pub');});
test('verified organization and publication keys cannot be overridden by interaction payload',()=>{const f=observe('channel-publication.interaction.observe');Object.assign(f.command.payload,{org:'other',publicationId:'other',interactionId:'i1',senderRef:'sender',contentRef:'content'});const r=transition(f.state,f.command,f.context);assert.equal(r.result.interaction.org,'org');assert.equal(r.result.interaction.publicationId,'pub');});
for(const [label,change] of [['different grant target',f=>f.context.grant.publicationId='other'],['different grant actor',f=>f.context.grant.principal='other'],['grant expired',f=>f.context.grant.validUntil='2026-01-01'],['grant revoked',f=>f.context.grant.revoked=true],['grant purpose',f=>f.context.grant.purpose='private-message'],['source expired',f=>f.context.sourceBinding.validUntil='2026-01-01'],['source future',f=>f.context.sourceBinding.validFrom='2027-01-01'],['source target',f=>f.context.sourceBinding.publicationId='other'],['source revoked',f=>f.context.sourceBinding.revoked=true],['source missing',f=>delete f.context.sourceBinding],['hold',f=>f.context.hold=true]])test(`fail closed ${label}`,()=>{const f=fixture();change(f);assert.throws(()=>transition(f.state,f.command,f.context));});
for(const action of ['channel-publication.effect.reconcile','channel-publication.interaction.observe'])test(`Supply Acquisition cannot ${action}`,()=>{const f=observe(action);f.context.department='supply-acquisition';assert.throws(()=>transition(f.state,f.command,f.context),/status read only/);});
test('Supply Acquisition may observe scoped status only',()=>{const f=observe();f.context.department='supply-acquisition';assert.equal(transition(f.state,f.command,f.context).result.status,'PUBLISHED');});
for(const action of ['channel-publication.effect.reconcile','channel-publication.interaction.observe'])test(`Customer Service cannot ${action}`,()=>{const f=observe(action);f.context.department='customer-service';assert.throws(()=>transition(f.state,f.command,f.context),/Marketing owns/);});
test('approval cannot omit approving principal',()=>{const f=fixture();delete f.context.approval.principal;assert.throws(()=>transition(f.state,f.command,f.context));});
for(const [label,change] of [['source conflict',f=>f.context.sourceBinding.conflict=true],['source hold',f=>f.context.sourceBinding.hold=true],['unspecified source conflict',f=>delete f.context.sourceBinding.conflict],['unspecified source hold',f=>delete f.context.sourceBinding.hold]])test(`fail closed ${label}`,()=>{const f=fixture();change(f);assert.throws(()=>transition(f.state,f.command,f.context),/conflict-free unheld/);});
for(const [label,change] of [['missing grant revocation proof',f=>delete f.context.grant.revoked],['missing source revocation proof',f=>delete f.context.sourceBinding.revoked],['missing hold proof',f=>delete f.context.hold],['missing emergency stop proof',f=>delete f.context.emergencyStop],['missing approval revocation proof',f=>delete f.context.approval.revoked]])test(`fail closed ${label}`,()=>{const f=fixture();change(f);assert.throws(()=>transition(f.state,f.command,f.context));});
